export const FETCH_POSTS = 'FETCH_POSTS';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const CREATE_POST = 'CREATE_POST';

export const CHESS_MOVE = 'CHESS_MOVE';

export const FETCH_MEMBERS = 'FETCH_MEMBERS';
export const FETCH_UNAPPROVED_MEMBERS = 'FETCH_UNAPPROVED_MEMBERS'
export const CREATE_MEMBERS  = 'CREATE_MEMBERS';
export const DELETE_MEMBERS = 'DELETE_MEMBERS';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const AUTH_CHANGED = 'AUTH_CHANGED';
export const APPROVAL_PENDING = 'APPROVAL_PENDING';
export const APPROVED = 'APPROVED';


// CHESS ACTIONS FOR CURRENT GAME
export const FLIP_BOARD_CURRENT_GAME = "FLIP_BOARD_CURRENT_GAME";
export const NEXT_MOVE_CURRENT_GAME = "NEXT_MOVE_CURRENT_GAME";
export const PREVIOUS_MOVE_CURRENT_GAME = "PREVOUS_MOVE_CURRENT_GAME";
export const FIRST_MOVE_CURRENT_GAME = "FIRST_MOVE_CURRENT_GAME";
export const LAST_MOVE_CURRENT_GAME = "LAST_MOVE_CURRENT_GAME";
export const START_NEW_GAME = "START_NEW_GAME";
export const JUMP_TO_MOVE_CURRENT_GAME =  "JUMP_TO_MOVE_CURRENT_GAME";

